export const GET_ERRORS = 'GET_ERRORS';
export const USER_LOADING = 'USER_LOADING';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const START_TIMER = 'START_TIMER';
export const STOP_TIMER = 'STOP_TIMER';
export const UPDATE_TIME_REMAINING = 'UPDATE_TIME'; //?
export const NEXT_TIMER ='NEXT_TIMER';
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
export const RESET_CURRENT_TIMER = 'RESET_CURRENT_TIMER';
export const RESET_APP = 'RESET_APP'; //?
export const TOGGLE_SETTINGS_DISPLAY = 'TOGGLE_SETTINGS_DISPLAY';