export const UPDATE_ERRORS = 'UPDATE_ERRORS';

export const USER_LOADING = 'USER_LOADING';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const UPDATE_CHART_SETTINGS = 'UPDATE_CHART_SETTINGS';
export const TOGGLE_CHART_SETTINGS = 'TOGGLE_CHART_SETTINGS';
export const CHART_LOADING = 'CHART_LOADING';
export const UPDATE_CHART_TASKS = 'UPDATE_CHART_TASKS';

export const START_TIMER = 'START_TIMER';
export const STOP_TIMER = 'STOP_TIMER';
export const UPDATE_TIME_LEFT = 'UPDATE_TIME_LEFT';
export const NEXT_TIMER ='NEXT_TIMER';
export const RESET_CURRENT_TIMER = 'RESET_CURRENT_TIMER';
export const ADD_COMPLETED_TASK = 'ADD_COMPLETED_TASK';
export const CLEAR_COMPLETED_TASKS = 'CLEAR_COMPLETED_TASKS';
export const UPDATE_COMPLETED_TASKS = 'SAVE_COMPLETED_TASKS';
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
export const TOGGLE_TIMER_SETTINGS = 'TOGGLE_TIMER_SETTINGS';
export const TIMER_LOADING = 'TIMER_LOADING';
export const TIMER_LOADED = 'TIMER_LOADED';